# manifests/application.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: application
spec:
  replicas: 3 # High Availability and Scalability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Ensures one extra pod can be created during update
      maxUnavailable: 0 # Ensures no pods are taken down until new ones are ready (Zero-Downtime)
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: web-server
        image: nginx:1.23.4-alpine # Specify version for controlled updates
        resources: # Proper resource requests and limits
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    # Use HTTPS redirect if TLS is enabled (requires a secret)
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
spec:
  ingressClassName: nginx # Must match the installed Ingress Controller
  rules:
  - host: myapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application-service
            port:
              number: 80